PA1_template - Rebecca Porphirio - March 8, 2016
Loading and preprocessing the data
-
```{r echo=FALSE}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r message=FALSE}
#loading due libraries
library(dplyr)
library(ggplot2)
library(lubridate)

#loading raw dataset
activity <- read.csv("activity.csv",header=TRUE,sep=",",stringsAsFactors=FALSE)
#transforming character variable into date class
activity$date <- as.Date(as.character(activity$date),"%Y-%m-%d")

head(activity)
```

What is the mean and the total number of steps taken per day?
-

```{r message=FALSE, fig.width=10,fig.height=5}
#Calculating total number of steps taken per day
days <- 
  activity %>%
  group_by(date) %>%
  summarize(steps=sum(steps,na.rm=TRUE),
            steps_mean=sum(steps,na.rm=TRUE)/n())
sum(days$steps,na.rm=TRUE)

#Ploting total number of steps taken each day
options(scipen=999)    #removing scientific notations
ggplot(days, aes(date, steps)) + 
  geom_bar(stat="identity", fill="burlywood1",color="brown3") +
  xlab("") + 
  ylab("Steps taken") +
  ggtitle("Total number of steps taken each day")

#Calculating mean and median of the total number of steps taken per day
sum(days$steps,na.rm=TRUE)/nrow(days)
median(days$steps)
```

```{r echo=FALSE}
p1 <- ggplot(days, aes(date, steps)) + 
  geom_bar(stat="identity", fill="burlywood1",color="brown3") +
  xlab("") + 
  ylab("Steps taken") +
  ggtitle("Total number of steps taken each day")
```

What is the average daily activity pattern?
-

```{r message=FALSE, fig.width=10,fig.height=5}
#Plotting a time series of the 5-minute interval and the average number of steps taken, averaged across all
#days 
ggplot(days, aes(date, steps_mean)) + geom_line(color="cadetblue3") +
  xlab("") + ylab("Steps taken") +
  ggtitle("Average number of steps taken each day")

#Creating a separate dataset
intervals <- 
  activity %>%
  group_by(interval) %>%
  summarize(steps=sum(steps,na.rm=TRUE),
            steps_mean=mean(steps,na.rm=TRUE)/n())

#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
intervals[which.max(intervals$steps_mean),"interval"]
```

Imputing missing values
-

```{r message=FALSE,fig.width=10,fig.height=10}
#What is the total number of missing values in the dataset?
length(which(is.na(activity$steps)))
length(which(is.na(activity$steps)))/nrow(activity)

#Creating new dataset equal to the original dataset but with the missing data filled in
steps_fixed <-
  activity %>%
  group_by(interval) %>%
  summarize(steps_mean=sum(steps,na.rm=TRUE)/n())
activity_fixed <-
  activity %>%
  mutate(steps_fixed=ifelse(is.na(steps),steps_fixed$steps_mean,steps))

#Creating histogram of the total number of steps taken each day
days_fixed <- 
  activity_fixed %>%
  group_by(date) %>%
  summarize(steps=sum(steps_fixed,na.rm=TRUE),
            steps_mean=sum(steps_fixed,na.rm=TRUE)/n())
p2 <- ggplot(days_fixed, aes(date, steps)) + 
  geom_bar(stat="identity", fill="lightcoral",color="lightpink") +
  xlab("") + 
  ylab("Steps taken") +
  ggtitle("Total number of steps taken each day- NAs fixed")
multiplot(p1,p2) #using the multiplot function to build two graphics at the same time. 

#Calculating mean and median total number of steps taken per day in new dataset
sum(days_fixed$steps,na.rm=TRUE)/nrow(days)
median(days_fixed$steps)

#Impact of imputing missing data on the estimates of the total daily number of steps
#Mean increased 13% but median hasn't moved.
#It changes most on the beginning of November where there's most of the NAs.
```

Are there differences in activity patterns between weekdays and weekends?
-

```{r message=FALSE, fig.width=10,fig.height=5}
#Creating a dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday 
#or weekend day
weekdays_weekends <-
  activity %>%
  mutate(day_type=ifelse(weekdays(activity$date)=="Saturday" | 
                           weekdays(activity$date)=="Sunday","Weekend","Weekday")) %>%
  group_by(day_type,interval) %>%
  summarize(steps=sum(steps,na.rm=TRUE),
            steps_mean=sum(steps,na.rm=TRUE)/n())

#Creating a panel plot containing a time series plot  of the 5-minute interval and the average number of 
#steps taken, averaged across all weekday days or weekend days
ggplot(weekdays_weekends, aes(factor(interval), steps, fill = factor(day_type))) + 
  geom_bar(stat="identity") +
  facet_grid(.~day_type) +
  scale_fill_hue(name="Day Type",labels=c("Weekday","Weekend")) +
  scale_x_discrete(breaks=NULL) + 
  xlab("5-minute intervals") + 
  ylab("Steps taken") +
  ggtitle("Average number of steps taken per 5-minute interval across weekdays and weekends")
```
